import os
import subprocess
from pathlib import Path
from typing import List, Dict, Optional
from dataclasses import dataclass
from .generator import GeneratedTestSuite

@dataclass
class WriteResult:
    output_path: str
    functions_tested: List[str]
    test_cases_written: int
    merged: bool

def _format_with_black(file_path: str):
    try:
        subprocess.run(["black", file_path], check=False, capture_output=True)
    except FileNotFoundError:
        pass # Black not installed

def write_tests(
    suites: List[GeneratedTestSuite],
    source_file: str,
    output_path: str,
    merge_mode: bool = False
) -> WriteResult:
    """Writes or merges generated test cases into the target test file."""
    output_file = Path(output_path)
    source_module = Path(source_file).stem
    
    existing_content = ""
    if merge_mode and output_file.exists():
        with open(output_file, "r", encoding="utf-8") as f:
            existing_content = f.read()

    new_imports = set()
    for suite in suites:
        new_imports.update(suite.imports_needed)
    
    # Header and standard imports
    content_lines = []
    if not existing_content:
        content_lines.append("# Generated by testgen-ai")
        content_lines.append("import pytest")
        content_lines.append(f"from {source_module} import *")
        for imp in sorted(new_imports):
            if imp not in ["import pytest"]:
                content_lines.append(imp)
        content_lines.append("\n")
    else:
        # Simple merge: Append new imports at top if missing (basic string check)
        # and append new tests at the bottom
        for imp in sorted(new_imports):
            if imp not in existing_content:
                content_lines.insert(0, imp)
        content_lines.append(existing_content.rstrip())
        content_lines.append("\n\n# New tests added by testgen-ai\n")

    functions_tested = []
    test_count = 0
    
    for suite in suites:
        functions_tested.append(suite.function_name)
        for tc in suite.test_cases:
            content_lines.append(f"def {tc.name}():")
            content_lines.append(f'    """{tc.description}"""')
            # Indent the generated code
            indented_code = "\n".join([f"    {line}" for line in tc.code.strip().splitlines()])
            content_lines.append(indented_code)
            content_lines.append("\n")
            test_count += 1

    final_content = "\n".join(content_lines)
    
    output_file.parent.mkdir(parents=True, exist_ok=True)
    with open(output_file, "w", encoding="utf-8") as f:
        f.write(final_content)
    
    _format_with_black(output_path)
    
    return WriteResult(
        output_path=str(output_file.absolute()),
        functions_tested=functions_tested,
        test_cases_written=test_count,
        merged=merge_mode and bool(existing_content)
    )
